---
title: "Analysis"
format: html
execute:
  eval: true
---

# Notes

Plots for my PhD thesis.

The analysis pipeline needs to be run at least once to find conformations
that are not to be sampled by the umbrella sampling (`wethyd_us_to_discard.csv`),
after which the WHAM of the umbrella sampling in `index.qmd` need to be (re)run.

# Setup

```{python}
from plotnine import *  # pyright: ignore
import pandas as pd
import numpy as np
from hamilton import driver
import scipy.stats as stats
import src.analysis as analysis
from src.analysis_utils import ix_cols
import src.analysis_utils as au
import src.steps as st
from src.constants import HAMILTON_CACHE
from src.style import (
    HITS_CYAN_LIGHT,
    HITS_DARKBLUE,
    HITS_GREEN,
    HITS_MAGENTA,
    HITS_SIGNALBLUE,
    MPI_DARK_GREY,
    MPI_GREEN,
    MPI_DARK_GREY,
    default_colors,
    DPI,
    single_column,
    double_column,
)
from src.analysis import NEW_IXS_C
_ = NEW_IXS_C

import logging
logging.basicConfig(level=logging.INFO)

envs = st.setup_envs()
new_envs = [e for e in envs if int(e["triple_ix_c_carbonyl"]) in NEW_IXS_C]
og_envs = [e for e in envs if int(e["triple_ix_c_carbonyl"]) not in NEW_IXS_C]
OG_IXS_C = [int(env["triple_ix_c_carbonyl"]) for env in og_envs]
OG_IXS_N = [int(env["triple_ix_n_peptide"]) for env in og_envs]

cutoff = 0.155
sum_cutoff = 0.277
filter_to_discard = "c_o_carb > @cutoff or (c_o_carb + c_o_oh) < @sum_cutoff"
filter_to_keep = "c_o_carb <= @cutoff and (c_o_carb + c_o_oh) >= @sum_cutoff"

# TS1
base_x = 0.45
base_w = 0.02
ts_x = 0.18
ts_w = 0.015
ti_x = 0.15
ti_w = 0.015

# baseline for TS2 profile
ts2_base_x = 0.15
ts2_base_w = 0.02
ts2_ts_x = 0.175
ts2_ts_w = 0.015
ts2_ti_x = 0.145
ts2_ti_w = 0.015
```

# Pipeline

```{python}
dr = (
    driver.Builder()
    .with_modules(analysis)
    .with_cache(
        path=HAMILTON_CACHE,
    )
    .build()
)

final_vars = [
    "envs",
    "parameters",
    "frame_cwds",
    "example_equilibration",
    "wethyd_us_energies",
    "parameters",
    "wethyd_choices",
    "wethyd_us_hist",
    "wethyd_us_prof",
    "wethyd_us_comb",
    "wetbreak_us",
    "wetbreak_us_comb",
    "break_us_distances",
    "break_us_protons"
]

result = dr.execute(
  final_vars=final_vars # pyright: ignore
)
```

```{python}
dr.visualize_execution(final_vars=final_vars)
```

# Results

```{python}
choices = result["wethyd_choices"]
eq = result["example_equilibration"]

energies: pd.DataFrame = result["wethyd_us_energies"]
hist = result["wethyd_us_hist"]
prof = result["wethyd_us_prof"]

hist_comb, prof_comb = result["wethyd_us_comb"]
prof_comb: pd.DataFrame
hist_comb: pd.DataFrame

hist_break, prof_break = result["wetbreak_us_comb"]
prof_break: pd.DataFrame
hist_break: pd.DataFrame

prof_break = prof_break.query("E.notna() and E != 0.0").copy()
prof_break["E"] = prof_break.groupby(["resname_c", "resname_n", "system"])["E"].transform(
    lambda x: x - x[(prof_break["x"] > ts2_base_x - ts2_base_w) & (prof_break["x"] < ts2_base_x + ts2_base_w)].mean()
)
prof_break['resnames'] = prof_break['resname_c'] + "-" + prof_break['resname_n']

break_protons: pd.DataFrame = result["break_us_protons"].query("n_h_oh.notna()")
break_protons['n_h_carboxyl'] = break_protons['n_h_oc'] + break_protons['n_h_oh']
break_protons['n_h_amino'] = break_protons['n_h_n']
break_protons = break_protons.drop(columns=['n_h_oc', 'n_h_oh', 'n_h_n'])
break_protons = break_protons.melt(
    id_vars=ix_cols,
    value_vars=["n_h_qw", "n_h_carboxyl", "n_h_amino"],
    var_name="type",
    value_name="n",
)
break_protons = break_protons.query("type != 'n_h_qw'")
break_protons = au.apply_group_names(break_protons)
break_protons['type'] = break_protons['type'].map({'n_h_carboxyl': 'carboxyl group', 'n_h_amino': 'amino group'}) # pyright: ignore
break_protons['type'] = break_protons['type'].astype("category")
```

## Equilibration

```{python}
p = (
  ggplot(eq, aes(x='time', y='d'))
  + geom_line()
  + labs(x = "time [ps]", y = "distance [nm]")
)
p.show()
p.save("./plots/triple_equilibration.png", dpi=DPI, width=single_column, height=single_column*0.6)
```

## WIP

### HBonds

```{python}
hbonds: pd.DataFrame = energies.groupby(ix_cols)[["n_hb"]].mean().reset_index()
hbonds['conf_d'] = hbonds['conf_d'].astype(float)
```

```{python}
p = (
  ggplot(hbonds, aes(x='conf_d', y='n_hb', group='system', color='system'))
  + geom_point()
  + geom_smooth(method='loess', se=False, span=0.1, color="black")
  + facet_wrap("~system")
)
p.show()
```

## Angles of the Peptide Bonds

```{python}
import MDAnalysis as mda
from math import degrees
import pandas as pd
import numpy as np
```

```{python}
def vis_carbonyl_orientation(u):
  nterm = u.select_atoms('resname ACE and name CH3').center(weights=None)
  cterm = u.select_atoms('resname NME and name CH3').center(weights=None)
  axis = cterm - nterm

  cs = u.select_atoms('not (resname ACE) and not (resname NME) and name C')
  ns = u.select_atoms('not (resname ACE ) and not (resname NME) and name N')
  os = u.select_atoms('not (resname ACE ) and not (resname NME) and name O')
# remove c of last residue before NME and n of first residue after ACE
# to avoid spanning chains
  aces = u.select_atoms('resname ACE and name C').resids
  nmes = u.select_atoms('resname NME and name N').resids

  angles_c_n = []
  angles_c_o = []
  o_distances = []
  c_distances = []
  for i in range(len(cs)-1):
    c = cs[i].position
    n = ns[i+1].position
    o = os[i].position
    peptide_bond = n - c
    carbonyl = o - c

    angle_c_n = degrees(np.arccos(np.dot(axis, peptide_bond) / (np.linalg.norm(axis) * np.linalg.norm(peptide_bond))))
    angles_c_n.append(angle_c_n)

    angle_carbonyl = degrees(np.arccos(np.dot(axis, carbonyl) / (np.linalg.norm(axis) * np.linalg.norm(carbonyl))))
    angles_c_o.append(angle_carbonyl)

    # distance of the carbonyl O to the axis
    o_distance = np.linalg.norm(np.cross(axis, o - nterm)) / np.linalg.norm(axis)
    o_distances.append(o_distance)
    # distance of the carbonyl C to the axis
    c_distance = np.linalg.norm(np.cross(axis, c - nterm)) / np.linalg.norm(axis)
    c_distances.append(c_distance)

  df = pd.DataFrame({'angle_c_o': angles_c_o, 'angle_c_n': angles_c_n, 'o_distance': o_distances, 'c_distance': c_distances, 'i': range(len(angles_c_o)), 'ix_c': cs.ix[:-1] })
  df['o-c'] = df['o_distance'] - df['c_distance']
  df['is_in_sites'] = df['ix_c'].isin(OG_IXS_C)
  df['is_in_new_sites'] = df['ix_c'].isin(NEW_IXS_C)

  return df

def plot_c_o(df: pd.DataFrame):
  df['o-c'] = df['o-c']*0.1  # convert to nm
  average_o_c = df['o-c'].mean()
  print(average_o_c)
  p = (
    ggplot(df, aes(x='i', y='o-c'))
    + geom_line()
    + geom_point()
    + geom_point(data=df.query("is_in_sites"), color='red', size=2)
    + geom_point(data=df.query("is_in_new_sites"), color='blue', size=2)
    + geom_hline(yintercept=average_o_c, linetype='dashed', color='black')
    + labs(x = "peptide bond index", y = "d(O-axis) - d(C-axis) [nm]")
  )
  return p
```


```{python}
#| eval: false
u = mda.Universe("./assets/triple.pdb")
df = vis_carbonyl_orientation(u)
p = plot_c_o(df)
p.show()
oc = df['o-c']
stats.ttest_1samp(oc, 0)
```

how about under force?

```{python}
u = mda.Universe("./run_6/f-603/ixs-178-180/triple/frame-96/eq.gro")
df = vis_carbonyl_orientation(u)
p = plot_c_o(df)
p.show()
oc = df['o-c']
stats.ttest_1samp(oc, 0)
p.save("./plots/carbonyl_orientation_example.png", dpi=DPI, width=single_column, height=single_column*0.6)
p.save("./plots/carbonyl_orientation_example.svg", dpi=72, width=single_column, height=single_column*0.6)
```

```{python}
df.query("is_in_sites")
```

```{python}
df.query("is_in_sites")
```

## How much data are we working with from the US?


```{python}
counts = energies.groupby(["ix_c", "ix_n", "system", "frame"]).size().reset_index(name='n').drop(columns=['n']).groupby(["ix_c", "ix_n", "system"]).size().reset_index(name='n_starting_frames') # pyright: ignore
print(counts)
```

```{python}
n_sites = counts.groupby(["ix_c", "ix_n"]).size().shape[0]
print(n_sites)
```

At least 5 starting frames per site and system, maximum of 10.
Most have around 8.

```{python}
p = (
    ggplot(counts, aes(x="n_starting_frames"))
    + geom_bar(fill='black', width=0.8)
    + scale_x_continuous(breaks=range(5, 11), minor_breaks=None)
    + scale_y_continuous(expand=(0,0,0.05,0))
    + labs(x="N", y="Count")
)
p.show()
p.save("./plots/wethyd_us_n_starting_frames_hist.png", dpi=DPI, width=single_column, height=single_column*0.6)
p.save("./plots/wethyd_us_n_starting_frames_hist.svg", dpi=DPI, width=single_column, height=single_column*0.6)
```

How many US windows do we have per site and system?
Characterized by the target distance conf_d and the extraction time conf_t.


```{python}
time_points = energies.groupby(ix_cols).size().reset_index(name='n_time_points') # pyright: ignore
time_points["sampling time"] = time_points["n_time_points"] * 0.01  # in ps
```

Total sampling time


```{python}
total_sampling_time = time_points["sampling time"].sum()
print(f"Total sampling time: {total_sampling_time/1000:.2f} ns")
```

Most windows of the first batch of sites have the full 500 time points, which is 5 ps of sampling.
Later sites will only have 100 at the start and will be extended if the resources allow it.

```{python}
p = (
    ggplot(time_points, aes(x="sampling time"))
    + geom_histogram(fill='black')
    + labs(x="Sampling time [ps]", y="Count")
    + scale_x_continuous(breaks=range(0, 6, 1), minor_breaks=None)
    + scale_y_continuous(expand=(0,0,0.05,0))
)
p.show()
p.save("./plots/wethyd_us_n_time_points_hist.png", dpi=DPI, width=single_column, height=single_column*0.6)
p.save("./plots/wethyd_us_n_time_points_hist.svg", dpi=DPI, width=single_column, height=single_column*0.6)
```


```{python}
windows = time_points.groupby(["ix_c", "ix_n", "system", "frame"]).size().reset_index(name='n_windows') # pyright: ignore
```

Most sites also have the full set of 50 umbrella windows.

```{python}
p = (
    ggplot(windows, aes(x="n_windows"))
    + geom_histogram(fill='black')
    + scale_y_continuous(expand=(0,0,0.05,0))
)
p.show()
p.save("./plots/wethyd_us_n_windows_hist.png", dpi=DPI, width=single_column, height=single_column*0.6)
p.save("./plots/wethyd_us_n_windows_hist.svg", dpi=DPI, width=single_column, height=single_column*0.6)
```

## TI

What trajectories need to be skipped because the TI doesn't form i.e. the carbonyl O just leaves and is replace by the attacking OH-?

### Distance of C=O and C-OH, Find to_discard

```{python}
co_distances: pd.DataFrame = result["wethyd_us_energies"].groupby(ix_cols)[["c_o_carb", "c_o_oh"]].mean().reset_index() # pyright: ignore
co_distances["to_filter"] = co_distances.eval(filter_to_discard)
```

```{python}
fraction_discarded = len(co_distances.query("to_filter")) / len(co_distances)
print(fraction_discarded)
```

```{python}
p = (
    ggplot(co_distances, aes(x="c_o_oh", y="c_o_carb"))
    + geom_point(aes(color="to_filter"), alpha=0.3)
    + scale_color_manual(values={True: 'red', False: 'black'})
    + labs(x="d(C-OH) [nm]", y="d(C=O) [nm]", color="to filter")
    + scale_x_continuous(limits=(0.12, 0.5))
    + scale_y_continuous(limits=(0.12, 0.2))
    + guides(color=False)
)
p.save("./plots/wethyd_us_ti_filter.png", dpi=DPI, width=single_column, height=single_column*0.75)
p.save("./plots/wethyd_us_ti_filter.svg", dpi=72, width=single_column, height=single_column*0.75)
p.show()
```

```{python}
co_distances.query("to_filter").to_csv("./data/results/wethyd_us_to_discard.csv", index=False)
```

Discarding

```{python}
len(co_distances.query("to_filter"))
```

out of

```{python}
len(co_distances)
```

Umbrella windows.

### Histogram of bond lengths

<!-- TODO: this -->


## TI protonation states

### No filtering

Without discarding this looks like this:

```{python}
tiprots_raw = energies.groupby(ix_cols)[["n_h_oh", "n_h_oc", "n_h_qw"]].mean().reset_index()
tiprots_raw = au.melt_tiprots(tiprots_raw)
```

```{python}
def tiprot_plot(df: pd.DataFrame) -> ggplot:
    """Plot the tiprot data."""
    p = (
        ggplot(df, aes(x="conf_d", y="n"))
        + geom_line(aes(group='group', color='type'), alpha=0.3)
        + geom_smooth(aes(color='type'), method='loess', se=False, span=0.1)
        + facet_wrap("sys2", scales="free_y", ncol=4)
        + labs(x=r"$\text{d}~[\text{nm}]$",
               y=r"$\text{n}_{\text{H}^+}$",
               color = r"$\text{n}_{\text{H}^+}$ at"
               )
        + scale_color_manual(values=default_colors)
        + scale_x_continuous(limits=(0.1, 0.5))
        + theme(legend_position="top")
    )
    return p
```

```{python}
p = tiprot_plot(tiprots_raw)
p.save("./plots/wethyd_us_tiprots_no_filter.png", dpi=DPI, width=double_column, height=double_column*0.75)
p.save("./plots/wethyd_us_tiprots_no_filter.svg", dpi=DPI, width=double_column, height=double_column*0.75)
p.show()
```

A special example of what can go wrong:
Pulling too far can lead to the carbonyl O leaving and being replaced by the OH-.
However, this is only the a problem for a couple of windows, which can easily be filtered out.

Example: GLY857-ALA858-triple

```{python}
p = tiprot_plot(tiprots_raw.query("sys2 == 'Gly857-Ala858-triple'"))
p.save("./plots/wethyd_us_tiprots_no_filter_example.png", dpi=DPI, width=single_column, height=single_column*0.75)
p.save("./plots/wethyd_us_tiprots_no_filter_example.svg", dpi=DPI, width=single_column, height=single_column*0.75)
p.show()
```

### With filtering

But with filtering out the bad trajectories it looks like this:

```{python}
tiprots = energies.query(filter_to_keep).groupby(ix_cols)[["n_h_oh", "n_h_oc", "n_h_qw"]].mean().reset_index()
tiprots = au.melt_tiprots(tiprots)
tiprots['label'] = r"$\text{n}_{\text{H}^+}$ at " + tiprots['type'].astype(str)
```

```{python}
p = tiprot_plot(tiprots)
p.save("./plots/wethyd_us_tiprots_filtered.png", dpi=DPI, width=double_column, height=double_column*0.75)
p.save("./plots/wethyd_us_tiprots_filtered.svg", dpi=DPI, width=double_column, height=double_column*0.75)
p.show()
```

The example above now looks like this:

```{python}
p = tiprot_plot(tiprots.query("sys2 == 'Gly857-Ala858-triple'"))
p.save("./plots/wethyd_us_tiprots_filtered_example.png", dpi=DPI, width=single_column, height=single_column*0.75)
p.save("./plots/wethyd_us_tiprots_filtered_example.svg", dpi=DPI, width=single_column, height=single_column*0.75)
p.show()
```

### Combined Protonation Single vs Triple

```{python}
p = (
    ggplot(tiprots, aes(x="conf_d", y="n"))
    + geom_rect(aes(xmin=ti_x - ti_w, xmax=ti_x + ti_w, ymin=-np.inf, ymax=np.inf), fill=MPI_DARK_GREY, alpha=0.01, inherit_aes=False)
    + geom_rect(aes(xmin=ts_x - ts_w, xmax=ts_x + ts_w, ymin=-np.inf, ymax=np.inf), fill=HITS_CYAN_LIGHT, alpha=0.01, inherit_aes=False)
    + geom_point(aes(group='group', color='system'), alpha=0.1, shape='.')
    # + geom_point(aes(group='group', color='type'), alpha=0.3)
    # + geom_smooth(aes(color='type'), method='loess', se=False, span=0.1)
    + geom_smooth(aes(color='system'), method='loess', se=False, span=0.1)
    + facet_wrap("~label", ncol=1, scales="free_y")
    + labs(x=r"$\text{d}~[\text{nm}]$",
           y=r"$\text{n}_{\text{H}^+}$",
           color = r"System"
           )
    + scale_x_continuous(limits=(0.12, 0.5))
    + scale_color_manual(values={"single": "black", "triple": MPI_GREEN})
    + theme(legend_position="top")
)
p.save("./plots/wethyd_us_tiprots_combined.png", dpi=DPI, width=single_column, height=single_column)
p.save("./plots/wethyd_us_tiprots_combined.svg", dpi=DPI, width=single_column, height=single_column)
p.show()
```

## Distances of the TI carbonyl O to various protons

```{python}
tidists = energies.query(filter_to_keep).groupby(ix_cols)[["solh", "proteinh", "qmh"]].mean().reset_index().melt(
    id_vars=ix_cols,
    value_vars=["solh", "proteinh", "qmh"],
    var_name="type",
    value_name="dist",
)
tidists = au.apply_group_names(tidists)
tidists["type"] = tidists["type"].map({ # pyright: ignore
    "solh": "MM Water",
    "proteinh": "Protein",
    "qmh": "QM Water"
})
```

```{python}
p = (
    ggplot(tidists, aes(x="conf_d", y="dist", color="type", goup="group"))
    + geom_line(aes(group='group', color='type'), alpha=0.3)
    + geom_smooth(aes(color='type'), method='loess', se=False, span=0.1)
    + facet_wrap("sys2", scales="free_y", ncol=4)
    + labs(x=r"$\text{d}~[\text{nm}]$",
           y=r"$\text{d}~[\text{nm}]$",
           color = r"d to closest H of"
           )
    + scale_color_manual(values={
        "MM Water": HITS_CYAN_LIGHT,
        "Protein": "black",
        "QM Water": HITS_MAGENTA
        })
    + scale_x_continuous(limits=(0.1, 0.5))
    + theme(legend_position="top")
)
p.save("./plots/wethyd_us_tidists.png", dpi=DPI, width=double_column, height=double_column*0.75)
p.save("./plots/wethyd_us_tidists.svg", dpi=DPI, width=double_column, height=double_column*0.75)
p.show()
```

## Umbrella sampling of TS1

minimum of the TI is around 0.151 - 0.155 nm

### Histograms

```{python}
p = (
  ggplot(hist_comb.query("ix_c == 178 and system == 'single' and count > 0.0"), aes(x='x', y='count', group='window'))
  + geom_line(alpha=0.3)
  + scale_x_continuous(limits=(0.1, 0.5))
  + labs(x=r"$\text{d}~[\text{nm}]$", y="Count")
)
p.save("./plots/wethyd_us_histogram_example.png", dpi=DPI, width=single_column, height=single_column*0.6)
p.save("./plots/wethyd_us_histogram_example.svg", dpi=DPI, width=single_column, height=single_column*0.6)
p.show()
```

### Profiles

filter out energies that are exactly equal to 0.0
substract baseline energy around x == 0.45 +- 0.02 per group 
(resname_c, resname_n, system)

Get delta E for x around `baseline_x` to minimum around `ti_x` for each group and
add a marker column if proline ('PRO') or hydroxy proline ('HYP') is present in the resname_c or resname_n
the marker will say C if the either is in resname_c and N if it is in resname_n, otherwise
it will say None.
Same for the maximum around `ts_x`.

```{python}
prof_comb = prof_comb.query("E.notna() and E != 0.0")
prof_comb["E"] = prof_comb.groupby(["resname_c", "resname_n", "ix_c", "ix_n", "system"])["E"].transform(
    lambda x: x - x[(prof_comb["x"] > base_x - base_w) & (prof_comb["x"] < base_x + base_w)].mean()
)
prof_comb['resnames'] = prof_comb['resname_c'] + "-" + prof_comb['resname_n']

p = (
    ggplot(prof_comb, aes(x="x", y="E", color="system", group="system"))
    + geom_rect(aes(xmin=ts_x - ts_w, xmax=ts_x + ts_w, ymin=-np.inf, ymax=np.inf), fill=HITS_CYAN_LIGHT, alpha=0.01, inherit_aes=False)
    + geom_rect(aes(xmin=ti_x - ti_w, xmax=ti_x + ti_w, ymin=-np.inf, ymax=np.inf), fill=MPI_DARK_GREY, alpha=0.01, inherit_aes=False)
    + geom_ribbon(aes(ymin="E-dE", ymax="E+dE", fill='system'), alpha=0.4, color=None, outline_type='full')
    + geom_line()
    # + geom_point(size=0.5, show_legend=False)
    + facet_wrap("~resnames")
    + scale_color_manual(values={"single": "black", "triple": MPI_GREEN})
    + scale_fill_manual(values={"single": "black", "triple": MPI_GREEN})
    + labs(x=r"$\text{d}~[\text{nm}]$", y=r"$\Delta$G [kJ/mol]")
    + guides(
      color=guide_legend(title="System", position=(1,0), override_aes={'fill': None, 'size': 1.5}),
      fill=False
    )
)
p.save("./plots/wethyd_us_profiles.png", dpi=DPI, width=double_column, height=double_column*0.63)
p.save("./plots/wethyd_us_profiles.svg", dpi=DPI, width=double_column, height=double_column*0.63)
p.show()
```


```{python}
dE_to_ti = prof_comb.groupby(["resnames", "resname_c", "resname_n", "system"]).apply( # pyright: ignore
    lambda x: x.query("x > @ti_x - @ti_w and x < @ti_x + @ti_w")["E"].min() - x.query("x > @base_x - @base_w and x < @base_x + @base_w")["E"].mean(),
    include_groups=False
).reset_index(name="delta_E")

dE_to_ts1 = prof_comb.groupby(["resnames", "resname_c", "resname_n", "ix_c", "ix_n", "system"]).apply( # pyright: ignore
    lambda x: x.query("x > @ts_x - @ts_w and x < @ts_x + @ts_w")["E"].min() - x.query("x > @base_x - @base_w and x < @base_x + @base_w")["E"].mean(),
    include_groups=False
).reset_index(name="delta_E")
dE_to_ts1 = dE_to_ts1.dropna(subset=['delta_E'])

# only keep those that have both single and triple data
dE_to_ts1 = dE_to_ts1.groupby("resnames").filter(lambda x: x['system'].nunique() == 2).reset_index(drop=True)
dE_to_ts1_single = dE_to_ts1.query("system == 'single'").reset_index(drop=True)
dE_to_ts1_triple = dE_to_ts1.query("system == 'triple'").reset_index(drop=True)
```


### dE TS1

```{python}
test = stats.ttest_rel(dE_to_ts1_triple['delta_E'], dE_to_ts1_single['delta_E'], alternative='greater')
pvalue = f"{test.pvalue:0.2}" # type: ignore
print(test)
```

averages, SEM and SD

```{python}
dE_to_ts1.groupby("system")["delta_E"].agg(['mean', 'sem', 'std'])
```

are the residuals normally distributed?

```{python}
dE_to_ts1['residuals'] = dE_to_ts1.groupby(['resnames', 'ix_c'])['delta_E'].transform(
    lambda x: x - x.mean()
)
import matplotlib.pyplot as plt
import scipy.stats as stats
plt.figure()
stats.probplot(dE_to_ts1['residuals'], dist="norm", plot=plt)
plt.title("Q-Q plot of residuals of delta E TS1")
# plt.show()
```


```{python}
df: pd.DataFrame = dE_to_ts1.copy()
ddE = df.groupby(["resnames", "ix_c"]).apply( # pyright: ignore
    lambda x: x.query("system == 'triple'")["delta_E"].values[0] - x.query("system == 'single'")["delta_E"].values[0],
    include_groups=False
).reset_index(name="ddE")
df = df.join(ddE.set_index(['resnames', 'ix_c']), on=['resnames', "ix_c"], how='left')
```

should be the same as two sample related t-test

```{python}
stats.ttest_1samp(ddE['ddE'], 0, alternative='greater')
```

See <https://plotnine.org/reference/guide_colorbar.html> for colorbar and svg reasoning.

```{python}
p = (
    ggplot(df, aes(x="system", y="delta_E"))
    # + geom_line(aes(group='resnames'), color='black', alpha=0.5)
    + geom_line(aes(group='resnames', color='ddE'), size=1.5)
    + geom_point(size=3, fill=HITS_CYAN_LIGHT)
    + annotate("segment", x=1, xend=2, y=160, yend=160, color='black', size=1.1)
    + annotate("text", label=r"*", x=1.5, y=160, va='bottom', color='black', fontweight='bold', size=10, ha='center')
    # + annotate("text", label=rf"p-value: {pvalue}", x=1.5, y=160, va='bottom', color='black', fontweight='bold', size=10, ha='center')
    + labs(y=r"$\Delta$G (kJ/mol)", x="")
    + scale_y_continuous(limits=(0, 180))
    + scale_color_gradient2(low=HITS_DARKBLUE, mid="white", high=HITS_MAGENTA, midpoint=0, name=r"$\Delta\Delta$G (kJ/mol)")
    + guides(color=guide_colorbar(
      display='raster'
    ))
)
p.save("./plots/wethyd_us_deltaE_comparison.png", dpi=DPI, width=single_column, height=single_column*0.75)
p.save("./plots/wethyd_us_deltaE_comparison.svg", dpi=72, width=single_column, height=single_column*0.75)
p.show()
```


### dE TI

```{python}
df: pd.DataFrame = dE_to_ti.copy()
ddE = df.groupby(["resnames"]).apply( # pyright: ignore
    lambda x: x.query("system == 'triple'")["delta_E"].values[0] - x.query("system == 'single'")["delta_E"].values[0],
    include_groups=False
).reset_index(name="ddE")
df = df.join(ddE.set_index('resnames'), on='resnames', how='left')
```

should be the same as two sample related t-test

```{python}
stats.ttest_1samp(ddE['ddE'], 0, alternative='greater')
```

```{python}
p = (
    ggplot(df, aes(x="system", y="delta_E"))
    # + geom_line(aes(group='resnames'), color='black', alpha=0.5)
    + geom_line(aes(group='resnames', color='ddE'), size=1.5)
    + geom_point(size=3, fill=MPI_DARK_GREY)
    + labs(y=r"$\Delta$G (kJ/mol)", x="")
    + scale_y_continuous(limits=(0, 180))
    + scale_color_gradient2(low=HITS_DARKBLUE, mid="white", high=HITS_MAGENTA, midpoint=0, name=r"$\Delta\Delta$G (kJ/mol)")
    + guides(color=guide_colorbar(
      display='raster'
    ))
)
p.save("./plots/wethyd_us_deltaE_comparison_ti.png", dpi=DPI, width=single_column, height=single_column*0.75)
p.save("./plots/wethyd_us_deltaE_comparison_ti.svg", dpi=72, width=single_column, height=single_column*0.75)
p.show()
```

### Individual starting points

```{python}
hist: pd.DataFrame = result["wethyd_us_hist"]
prof: pd.DataFrame = result["wethyd_us_prof"]
```

```{python}
prof = prof.query("E.notna() and E != 0.0").copy()
prof["E"] = prof.groupby(["resname_c", "resname_n", "ix_c", "ix_n", "system", "frame"])["E"].transform(
    lambda x: x - x[(prof["x"] > base_x - base_w) & (prof["x"] < base_x + base_w)].mean()
)
prof['resnames'] = prof['resname_c'] + "-" + prof['resname_n']
```

```{python}
#| eval: false
p = (
    ggplot(prof, aes(x="x", y="E", color="system", group="system"))
    # shade the TS1 region
    + geom_rect(aes(xmin=ts_x - ts_w, xmax=ts_x + ts_w, ymin=-np.inf, ymax=np.inf), fill=HITS_CYAN_LIGHT, alpha=0.01, inherit_aes=False)
    # shade the TI region
    + geom_rect(aes(xmin=ti_x - ti_w, xmax=ti_x + ti_w, ymin=-np.inf, ymax=np.inf), fill=MPI_DARK_GREY, alpha=0.01, inherit_aes=False)
    + geom_ribbon(aes(ymin="E-dE", ymax="E+dE", fill='system'), alpha=0.4, color=None, outline_type='full')
    + geom_line()
    + geom_point()
    + facet_wrap("~ix_c+frame", as_table=False)
    + scale_color_manual(values={"single": "black", "triple": MPI_GREEN})
    + scale_fill_manual(values={"single": "black", "triple": MPI_GREEN})
    + labs(x=r"$\text{d}~[\text{nm}]$", y="E [kJ/mol]")
)
p.show()
```

Examples for likely subsitution reaction:
- ix_c 178, frame 96, single

Example for likely nice TI:
- ix_c 178, frame 92, single
- ix_c 178, frame 97, triple

## Umbrella sampling of the Break (TS2)

### Histograms

### Profiles

```{python}
p = (
    ggplot(prof_break, aes(x="x", y="E", color="system", group="system"))
    + geom_ribbon(aes(ymin="E-dE", ymax="E+dE", fill='system'), alpha=0.4, color=None, outline_type='full')
    + geom_line()
    + geom_point()
    + facet_wrap("~resnames")
    + scale_color_manual(values={"single": "black", "triple": MPI_GREEN})
    + scale_fill_manual(values={"single": "black", "triple": MPI_GREEN})
    + labs(x=r"$\text{d}~[\text{nm}]$", y="E [kJ/mol]")
)
p.save("./plots/wetbreak_us_profiles.png", dpi=DPI, width=double_column, height=double_column*0.75)
p.save("./plots/wetbreak_us_profiles.svg", dpi=DPI, width=double_column, height=double_column*0.75)
p.show()
```

just Ala845-Gly846, Gly840-Ala841, Hyp851-Gly852

```{python}
p = (
    ggplot(prof_break.query("resnames in ['Ala845-Gly846', 'Gly840-Ala841', 'Hyp851-Gly852']"), aes(x="x", y="E", color="system", group="system"))
    + geom_ribbon(aes(ymin="E-dE", ymax="E+dE", fill='system'), alpha=0.4, color=None, outline_type='full')
    + geom_line()
    # + geom_point(show_legend=False)
    + facet_wrap("~resnames")
    + scale_color_manual(values={"single": "black", "triple": MPI_GREEN})
    + scale_fill_manual(values={"single": "black", "triple": MPI_GREEN})
    + labs(x=r"$\text{d}~[\text{nm}]$", y="E [kJ/mol]")
    + guides(
      color=guide_legend(title="System", position="top", override_aes={'fill': None, 'size': 1.5}),
      fill=False
    )
)
p.save("./plots/wetbreak_us_profiles_example.png", dpi=DPI, width=double_column*4/10, height=double_column*1/3)
p.save("./plots/wetbreak_us_profiles_example.svg", dpi=DPI, width=double_column*4/10, height=double_column*1/3)
p.show()
```

## Protonation States during Break

just Ala845-Gly846, Gly840-Ala841, Hyp851-Gly852

```{python}
df = break_protons.query("resnames in ['Ala845-Gly846', 'Gly840-Ala841', 'Hyp851-Gly852']")
```

```{python}
p = (
    ggplot(df, aes(x="conf_d", y="n"))
    # + geom_point(aes(group='group', color='type'), alpha=0.1)
    + geom_smooth(aes(color='type'), method='loess', se=False, span=0.12)
    + facet_wrap("sys2", scales="free_y")
    + labs(x=r"$\text{d}~[\text{nm}]$",
           y=r"$\text{n}_{\text{H}^+}$",
           color = r"$\text{n}_{\text{H}^+}$ at"
           )
    + scale_color_manual(
        values={
            "carboxyl group": HITS_SIGNALBLUE,
            "amino group": HITS_GREEN
        }
    )
    + scale_x_continuous(limits=(0.14, 0.5))
    + scale_y_continuous(breaks=np.arange(0, 4, 0.5), limits=(0, 3)) # pyright: ignore
    + theme(legend_position="top")
    + guides(
      color=guide_legend(position="top", override_aes={'fill': None, 'size': 1.5}),
      fill=False
    )
)
p.save("./plots/wetbreak_us_tiprots_example.png", dpi=DPI, width=double_column*6/10, height=double_column*1/3)
p.save("./plots/wetbreak_us_tiprots_example.svg", dpi=72, width=double_column*6/10, height=double_column*1/3)
p.show()
```

Extract theses ixs to use as example trajectories for visualization.

```{python}
df.ix_c.unique()
```

print unique ix_c and frame combinations to extract example trajectories later

```{python}
df[["ix_c", "frame"]].drop_duplicates().sort_values(by=["ix_c", "frame"]).reset_index(drop=True) # pyright: ignore
```

# Misc

Computational costs of umbrella sampling

```{python}
step_time_string = """
3600 , Feb 19 17:05:57
3700 , Feb 19 18:21:56
3800 , Feb 19 19:37:38
3900 , Feb 19 20:52:16
4000 , Feb 19 22:06:49
4100 , Feb 19 23:22:51
4200 , Feb 20 00:38:08
4300 , Feb 20 01:52:48
4400 , Feb 20 03:08:24
4500 , Feb 20 04:25:20
4600 , Feb 20 05:42:43
4700 , Feb 20 07:00:12
4800 , Feb 20 08:18:35
4900 , Feb 20 09:36:32
5000 , Feb 20 10:54:22
"""
import pandas as pd
from datetime import datetime
from datetime import timedelta
from io import StringIO
df = pd.read_csv(StringIO(step_time_string), header=None, names=['step', 'time'], skipinitialspace=True)
df['time'] = pd.to_datetime(df['time'], format="%b %d %H:%M:%S")
df = df.sort_values('step').reset_index(drop=True)
df['delta'] = df['time'].diff().fillna(pd.Timedelta(seconds=0))
df['delta_s'] = df['delta'].dt.total_seconds()
df['time_per_step_s'] = df['delta_s'] / (df['step'] - df['step'].shift(1)).fillna(1)
df['time_per_step_h'] = df['time_per_step_s'] / 3600
df['cumulative_time_h'] = df['time_per_step_h'].cumsum()
df['steps_per_hour'] = 1 / df['time_per_step_h'].replace(0, pd.NA)
print(df)
mean_s_per_step = df[1:]['time_per_step_s'].mean()
total_steps = 5000
total_hours = total_steps * mean_s_per_step / 3600
total_hours # ~= 60 hours
```

```{python}
n_windows = 50
n_frames = 8 # average number of starting frames
hours = total_hours * n_windows * n_frames
days = hours / 24
days # ~= 1000 days
```

```{python}
n_sites = 8
total_days = days * n_sites
total_days # ~= 8500 days
```

# Cleanup

To rerun certain hamilton nodes:

```{python}
#| eval: false
au.write_timestamp("hyd-energies")
au.write_timestamp("hyd-us-comb")
```

```{python}
import graphviz
dot = dr.display_all_functions()
dot: graphviz.Digraph
```

