# parsing { #src.parsing }

`parsing`



## Classes

| Name | Description |
| --- | --- |
| [Gro](#src.parsing.Gro) | A gromacs gro file |
| [GroAtom](#src.parsing.GroAtom) | An atom in a gromacs gro file |

### Gro { #src.parsing.Gro }

`parsing.Gro(self, title, atoms, box)`

A gromacs gro file

Lines contain the following information (top to bottom):
    - title string (free format string, optional time in ps after ‘t=’)
    - number of atoms (free format integer)
    - one line for each atom (fixed format, see GroAtom)
    - box vectors (free format, space separated reals), values: v1(x) v2(y) v3(z) v1(y) v1(z) v2(x) v2(z) v3(x) v3(y),
      the last 6 values may be omitted (they will be set to zero).
      GROMACS only supports boxes with v1(y)=v1(z)=v2(z)=0.

For Example:

```
MD of 2 waters, t= 0.0
    6
    1WATER  OW1    1   0.126   1.624   1.679  0.1227 -0.0580  0.0434
    1WATER  HW2    2   0.190   1.661   1.747  0.8085  0.3191 -0.7791
    1WATER  HW3    3   0.177   1.568   1.613 -0.9045 -2.6469  1.3180
    2WATER  OW1    4   1.275   0.053   0.622  0.2519  0.3140 -0.1734
    2WATER  HW2    5   1.337   0.002   0.680 -1.0641 -1.1349  0.0257
    2WATER  HW3    6   1.326   0.120   0.568  1.9427 -0.8216 -0.0244
   1.82060   1.82060   1.82060
```

### GroAtom { #src.parsing.GroAtom }

`parsing.GroAtom(self, residue_number, residue_name, atom_name, atom_number, position, velocity=None, ix=0)`

An atom in a gromacs gro file

The fixed format for each atom is:

    - residue number (5 positions, integer)
    - residue name (5 characters)
    - atom name (5 characters)
    - atom number (5 positions, integer)
    - position (in nm, x y z in 3 columns, each 8 positions with 3 decimal places)
    - velocity (in nm/ps (or km/s), x y z in 3 columns, each 8 positions with 4 decimal places)

e.g. C format: "%5d%-5s%5s%5d%8.3f%8.3f%8.3f%8.4f%8.4f%8.4f"

NOTE: never trust the atom numbers of a gro file! They wrap around at 99999.

#### Attributes

| Name           | Type   | Description                                                         |
|----------------|--------|---------------------------------------------------------------------|
| residue_number |        | The residue number                                                  |
| residue_name   |        | The residue name                                                    |
| atom_name      |        | The atom name                                                       |
| atom_number    |        | The atom number                                                     |
| position       |        | The position in nm                                                  |
| velocity       |        | The velocity in nm/ps                                               |
| ix             |        | The index of the atom in the gro file, 0-based, fed during parsing. |

#### Methods

| Name | Description |
| --- | --- |
| [angle](#src.parsing.GroAtom.angle) | Calculate the angle between three atoms |
| [distance](#src.parsing.GroAtom.distance) | Calculate the distance between two atoms |

##### angle { #src.parsing.GroAtom.angle }

`parsing.GroAtom.angle(left, right)`

Calculate the angle between three atoms

With self, left and right as positions s, l, r, the angle is calculated of
l -- s -- r
i.e. `self` is at the apex of the angle.
If the atoms are colliding, a warning is logged and 0 is returned.

###### Parameters

| Name    | Type                             | Description           | Default    |
|---------|----------------------------------|-----------------------|------------|
| `left`  | [GroAtom](`src.parsing.GroAtom`) | The first other atom  | _required_ |
| `right` | [GroAtom](`src.parsing.GroAtom`) | The second other atom | _required_ |

###### Returns

| Type             | Description          |
|------------------|----------------------|
| [float](`float`) | The angle in degrees |

##### distance { #src.parsing.GroAtom.distance }

`parsing.GroAtom.distance(other)`

Calculate the distance between two atoms

###### Parameters

| Name    | Type                             | Description    | Default    |
|---------|----------------------------------|----------------|------------|
| `other` | [GroAtom](`src.parsing.GroAtom`) | The other atom | _required_ |

###### Returns

| Type                 | Description                              |
|----------------------|------------------------------------------|
| [nm](`src.units.nm`) | The distance between the two atoms in nm |